"""
Django settings for DataSocial project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9u!x5e6l&m43x1g(kukgnfcj#_i!d%mgz0$n*u+e-i$t9j1=&0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django_crontab',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 用户注册应用
    'UserRegister',
    # 图形验证码应用
    'captcha',
    # 数据集应用
    'dataset',
    # 个人主页
    'homepage',
    # 任务中心
    'task',
]

# 中间件
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DataSocial.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DataSocial.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 采用mysql数据引擎
        'NAME': 'DataSocial',  # 数据库名称
        'HOST': 'xxx.xx.xx.xx',  # 服务器地址（已重置）
        'USER': 'xxxxxx（已重置）',
        'PASSWORD': 'xxxxxx（已重置）',
        'PORT': 'xxxxxx（已重置）'
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/


LANGUAGE_CODE = 'zh-hans'  # 配置中文

TIME_ZONE = 'Asia/Shanghai'  # 配置时间

USE_I18N = True

USE_L10N = True

USE_TZ = False  # 配置

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'static' ## 新增行
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, '/static/')  # 静态文件目录
]

# 图像验证码格式，可以自定义。
CAPTCHA_OUTPUT_FORMAT = u'%(text_field)s  %(image)s %(hidden_field)s'
# 添加干扰点、干扰线
CAPTCHA_NOISE_FUNCTIONS = (
    'captcha.helpers.noise_null',
    'captcha.helpers.noise_arcs',  # 干扰线
    'captcha.helpers.noise_dots',  # 干扰点
)
# 图片大小
CAPTCHA_IMAGE_SIZE = (100, 25)
# 背景颜色
CAPTCHA_BACKGROUND_COLOR = '#ffffff'
# 验证码的样式
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge'  # 随机字符
# CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge'    # 数学表达式
# 字符个数
CAPTCHA_LENGTH = 4
# 超时时间（分钟）
CAPTCHA_TIMEOUT = 1

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://:cjmredis@123.57.61.61:6379/1",  # 服务器地址
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100},  # 最大连接数
            "PASSWORD": "cjmredis",
        }
    }
}

# 数据集存储路径
DATASET_FILE_SAVE_ROOT = os.path.join(BASE_DIR, 'dataset_file_savedir')

# 任务数据集存储路径
TASK_DATASET_FILE_SAVE_ROOT = os.path.join(BASE_DIR, 'task_dataset_file_savedir')

# 任务回答
TASK_ANSWER_DATASET = os.path.join(BASE_DIR, 'task_answer_dataset')

# 定时函数
CRONJOBS = [
('0 5 * * *', 'task.task_change_status.task_change_status','>>/DataGo/projets/DataSocial/log/task_status_change_log.txt'),
]
