# Generated by Django 3.0.8 on 2020-12-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=15, unique=True)),
                ('user_telephone', models.CharField(max_length=11, unique=True)),
                ('user_email', models.CharField(max_length=25, unique=True)),
                ('user_password', models.CharField(max_length=15)),
                ('user_register_date', models.DateField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
