# Generated by Django 3.0.8 on 2020-12-22 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegister', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
